name = "nodescope-collector"
main = "workers/collector.js"
compatibility_date = "2026-10-01"

[[kv_namespaces]]
binding = "NODESCOPE_DATA"
id = "6f1b134fa8ad450dbfdc261981c2ee4c"

[triggers]
crons = ["0 */4 * * *", "*/2 * * * *"]
